name = "perseus-backend"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "perseus-wikimedia-db"
database_id = "cfc19d67-3206-4b89-a75b-0a5118425bed"
migrations_dir = "migrations"

[vars]
DEFAULT_WEEKLY_COST_LIMIT = "0.16"
